### PR TITLE
added goals to profile

### PR DESCRIPTION
**Pull request by Kellsonphilips**

### CODE REVIEW

**Comment by alisamadiii** [comment]
Thanks for it Philips Bro,
it is working fine...
image

**Comment by Kellsonphilips** [comment]
That's good, you can merge the PR right?

**Comment by Kellsonphilips** [comment]
ARe you going to merge the testing PR?

**Comment by alisamadiii** [comment]
NO @Kellsonphilips 

> ARe you going to merge the testing PR?

**Pull request merged**
