### PR TITLE
fix: Fixed the issue#1

### PR DESCRIPTION
**Pull request by bharathkalyans**
* The below snapshot provides the new outlook of the Dashboard page.

snapshot

* I think it looks good enough!!

### CODE REVIEW

**Comment by bharathkalyans** [comment]
* I think we should improve the docs regarding the project setup.
* **FirebaseConfig** and enabling **Google Authentication** in Firebase Dashboard should have been mentioned.
* It took me a couple of minutes, why I wasn't unable to sign in using Google SignIn 😅 even after setting up FirebaseConfig.

**Comment by bharathkalyans** [comment]
@AliReza1083 ??

**Comment by alisamadiii** [comment]
> * I think we should improve the docs regarding the project setup.
> * **FirebaseConfig** and enabling **Google Authentication** in Firebase Dashboard should have been mentioned.
> * It took me a couple of minutes, why I wasn't unable to sign in using Google SignIn 😅 even after setting up FirebaseConfig.

I do agree, Sorry for that.

**Comment by alisamadiii** [comment]
This project is from long time ago, I might change it and start using .env + Nextjs.

**Comment by bharathkalyans** [comment]
Sure @AliReza1083, would love to contribute to that as well.🙌🏼 Hoping it is going to be an open-source one.

**Pull request closed without merging**
